spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.141.19.123:3306/mall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 10.141.19.123:8848
  application:
    name: mall-member
  redis:
    host: 10.141.19.123
    port: 6379
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
server:
  port: 8000
