server:
  port: 8150
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 10.141.19.123:8848
  redis:
    host: 10.141.19.123
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis
