spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: mall-mabiao

  application:
    name: mall-third-party

server:
  port: 30000